/* ----------------------------------------------------------------------------
* This file was automatically generated by SWIG (http://www.swig.org).
* Version 3.0.12
*
* This file is not intended to be easily readable and contains a number of
* coding conventions designed to improve portability and efficiency. Do not make
* changes to this file unless you know what you are doing--modify the SWIG
* interface file instead.
* ----------------------------------------------------------------------------- */


#ifndef __cplusplus
typedef int bool;
#define true 1
#define false 0
#endif

#include <pocketsphinx.h>

typedef ps_decoder_t Decoder;
typedef ps_decoder_t SegmentList;
typedef ps_decoder_t NBestList;
typedef ps_lattice_t Lattice;



#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif

/* -----------------------------------------------------------------------------
*  This section contains generic SWIG labels for method/variable
*  declarations/attributes, and other compiler dependent labels.
* ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
* cast to void, which is a common idiom which we use to indicate that we
* are aware a variable isn't used.  So we just silence that warning.
* See: https://github.com/swig/swig/issues/192 for more discussion.
*/
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types:
* Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
    SWIG_CSharpApplicationException,
    SWIG_CSharpArithmeticException,
    SWIG_CSharpDivideByZeroException,
    SWIG_CSharpIndexOutOfRangeException,
    SWIG_CSharpInvalidCastException,
    SWIG_CSharpInvalidOperationException,
    SWIG_CSharpIOException,
    SWIG_CSharpNullReferenceException,
    SWIG_CSharpOutOfMemoryException,
    SWIG_CSharpOverflowException,
    SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
    SWIG_CSharpArgumentException,
    SWIG_CSharpArgumentNullException,
    SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
    SWIG_CSharpExceptionCodes code;
    SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
    SWIG_CSharpExceptionArgumentCodes code;
    SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
    { SWIG_CSharpApplicationException, NULL },
    { SWIG_CSharpArithmeticException, NULL },
    { SWIG_CSharpDivideByZeroException, NULL },
    { SWIG_CSharpIndexOutOfRangeException, NULL },
    { SWIG_CSharpInvalidCastException, NULL },
    { SWIG_CSharpInvalidOperationException, NULL },
    { SWIG_CSharpIOException, NULL },
    { SWIG_CSharpNullReferenceException, NULL },
    { SWIG_CSharpOutOfMemoryException, NULL },
    { SWIG_CSharpOverflowException, NULL },
    { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
    { SWIG_CSharpArgumentException, NULL },
    { SWIG_CSharpArgumentNullException, NULL },
    { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
    SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
    if ((size_t)code < sizeof(SWIG_csharp_exceptions) / sizeof(SWIG_CSharpException_t)) {
        callback = SWIG_csharp_exceptions[code].callback;
    }
    callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
    SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
    if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument) / sizeof(SWIG_CSharpExceptionArgument_t)) {
        callback = SWIG_csharp_exceptions_argument[code].callback;
    }
    callback(msg, param_name);
}


#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_PocketSphinx(
    SWIG_CSharpExceptionCallback_t applicationCallback,
    SWIG_CSharpExceptionCallback_t arithmeticCallback,
    SWIG_CSharpExceptionCallback_t divideByZeroCallback,
    SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback,
    SWIG_CSharpExceptionCallback_t invalidCastCallback,
    SWIG_CSharpExceptionCallback_t invalidOperationCallback,
    SWIG_CSharpExceptionCallback_t ioCallback,
    SWIG_CSharpExceptionCallback_t nullReferenceCallback,
    SWIG_CSharpExceptionCallback_t outOfMemoryCallback,
    SWIG_CSharpExceptionCallback_t overflowCallback,
    SWIG_CSharpExceptionCallback_t systemCallback) {
    SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
    SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
    SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
    SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
    SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
    SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
    SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
    SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
    SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
    SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
    SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_PocketSphinx(
    SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
    SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
    SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
    SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
    SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
    SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_PocketSphinx(SWIG_CSharpStringHelperCallback callback) {
    SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


// MattMatt2000: Stupid SWIG didn't generated these
// -----------------------------------------------------------------------

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13

SWIGINTERN void SWIG_CSharpException(int code, const char *msg) {
    if (code == SWIG_ValueError) {
        SWIG_CSharpExceptionArgumentCodes exception_code = SWIG_CSharpArgumentOutOfRangeException;
        SWIG_CSharpSetPendingExceptionArgument(exception_code, msg, 0);
    }
    else {
        SWIG_CSharpExceptionCodes exception_code = SWIG_CSharpApplicationException;
        switch (code) {
        case SWIG_MemoryError:
            exception_code = SWIG_CSharpOutOfMemoryException;
            break;
        case SWIG_IndexError:
            exception_code = SWIG_CSharpIndexOutOfRangeException;
            break;
        case SWIG_DivisionByZero:
            exception_code = SWIG_CSharpDivideByZeroException;
            break;
        case SWIG_IOError:
            exception_code = SWIG_CSharpIOException;
            break;
        case SWIG_OverflowError:
            exception_code = SWIG_CSharpOverflowException;
            break;
        case SWIG_RuntimeError:
        case SWIG_TypeError:
        case SWIG_SyntaxError:
        case SWIG_SystemError:
        case SWIG_UnknownError:
        default:
            exception_code = SWIG_CSharpApplicationException;
            break;
        }
        SWIG_CSharpSetPendingException(exception_code, msg);
    }
}

// -----------------------------------------------------------------------

typedef cmd_ln_t Config;
typedef feat_t Feature;
typedef fe_t FrontEnd;
typedef fsg_model_t FsgModel;
typedef logmath_t LogMath;
typedef ngram_model_t NGramModel;
typedef ngram_model_t NGramModelSet;



// TODO: make private with %immutable
typedef struct {
    char *hypstr;
    int best_score;
    int prob;
} Hypothesis;

typedef struct {
    char *word;
    int ascore;
    int lscore;
    int lback;
    int prob;
    int start_frame;
    int end_frame;
} Segment;

typedef struct {
    char *hypstr;
    int score;
} NBest;


SWIGINTERN Hypothesis *new_Hypothesis(char const *hypstr, int best_score, int prob) {
    Hypothesis *h = (Hypothesis *)ckd_malloc(sizeof *h);
    if (hypstr)
        h->hypstr = ckd_salloc(hypstr);
    else
        h->hypstr = NULL;
    h->best_score = best_score;
    h->prob = prob;
    return h;
}
SWIGINTERN void delete_Hypothesis(Hypothesis *self) {
    if (self->hypstr)
        ckd_free(self->hypstr);
    ckd_free(self);
}
SWIGINTERN Segment *Segment_fromIter(void *itor) {
    Segment *seg;
    if (!itor)
        return NULL;
    seg = (Segment *)ckd_malloc(sizeof(Segment));
    seg->word = ckd_salloc(ps_seg_word((ps_seg_t *)itor));
    seg->prob = ps_seg_prob((ps_seg_t *)itor, &(seg->ascore), &(seg->lscore), &(seg->lback));
    ps_seg_frames((ps_seg_t *)itor, &seg->start_frame, &seg->end_frame);
    return seg;
}
SWIGINTERN void delete_Segment(Segment *self) {
    ckd_free(self->word);
    ckd_free(self);
}
SWIGINTERN NBest *NBest_fromIter(void *itor) {
    NBest *nbest;
    if (!itor)
        return NULL;
    nbest = (NBest *)ckd_malloc(sizeof(NBest));
    nbest->hypstr = ckd_salloc(ps_nbest_hyp((ps_nbest_t *)itor, &(nbest->score)));
    return nbest;
}
SWIGINTERN Hypothesis *NBest_hyp(NBest *self) {
    return self->hypstr ? new_Hypothesis(self->hypstr, self->score, 0) : NULL;
}
SWIGINTERN void delete_NBest(NBest *self) {
    ckd_free(self->hypstr);
    ckd_free(self);
}

typedef struct {
    ps_seg_t *ptr;
} SegmentIterator;

SWIGINTERN SegmentIterator *new_SegmentIterator(ps_seg_t *ptr) {
    SegmentIterator *iter = (SegmentIterator *)ckd_malloc(sizeof *iter);
    iter->ptr = ptr;
    return iter;
}
SWIGINTERN void delete_SegmentIterator(SegmentIterator *self) {
    if (self->ptr)
        ps_seg_free(self->ptr);
    ckd_free(self);
}

typedef struct {
    ps_nbest_t *ptr;
} NBestIterator;

SWIGINTERN NBestIterator *new_NBestIterator(ps_nbest_t *ptr) {
    NBestIterator *iter = (NBestIterator *)ckd_malloc(sizeof *iter);
    iter->ptr = ptr;
    return iter;
}
SWIGINTERN void delete_NBestIterator(NBestIterator *self) {
    if (self->ptr)
        ps_nbest_free(self->ptr);
    ckd_free(self);
}
SWIGINTERN Decoder *new_Decoder__SWIG_0(int *errcode) {
    Decoder *d = ps_init(cmd_ln_init(NULL, ps_args(), FALSE, NULL));
    *errcode = d ? 0 : -1;
    return d;
}
SWIGINTERN Decoder *new_Decoder__SWIG_1(Config *config, int *errcode) {
    Decoder *d = ps_init(config);
    *errcode = d ? 0 : -1;
    return d;
}
SWIGINTERN void delete_Decoder(Decoder *self) {
    ps_free(self);
}
SWIGINTERN void Decoder_reinit(Decoder *self, Config *config, int *errcode) {
    *errcode = ps_reinit(self, config);
}
SWIGINTERN void Decoder_load_dict(Decoder *self, char const *fdict, char const *ffilter, char const *format, int *errcode) {
    *errcode = ps_load_dict(self, fdict, ffilter, format);
}
SWIGINTERN void Decoder_save_dict(Decoder *self, char const *dictfile, char const *format, int *errcode) {
    *errcode = ps_save_dict(self, dictfile, format);
}
SWIGINTERN void Decoder_add_word(Decoder *self, char const *word, char const *phones, int update, int *errcode) {
    *errcode = ps_add_word(self, word, phones, update);
}
SWIGINTERN char *Decoder_lookup_word(Decoder *self, char const *word) {
    return ps_lookup_word(self, word);
}
SWIGINTERN Lattice *Decoder_get_lattice(Decoder *self) {
    return ps_lattice_retain(ps_get_lattice(self));
}
SWIGINTERN Config *Decoder_get_config(Decoder *self) {
    return cmd_ln_retain(ps_get_config(self));
}
SWIGINTERN Config *Decoder_default_config(void) {
    return cmd_ln_parse_r(NULL, ps_args(), 0, NULL, FALSE);
}
SWIGINTERN Config *Decoder_file_config(char const *path) {
    return cmd_ln_parse_file_r(NULL, ps_args(), path, FALSE);
}
SWIGINTERN void Decoder_start_stream(Decoder *self, int *errcode) {
    *errcode = ps_start_stream(self);
}
SWIGINTERN void Decoder_start_utt(Decoder *self, int *errcode) {
    *errcode = ps_start_utt(self);
}
SWIGINTERN void Decoder_end_utt(Decoder *self, int *errcode) {
    *errcode = ps_end_utt(self);
}
SWIGINTERN int Decoder_process_raw(Decoder *self, unsigned char const *SDATA, int SIZE, bool no_search, bool full_utt, int *errcode) {
    return *errcode = ps_process_raw(self, (const int16 *)SDATA, SIZE / 2, no_search, full_utt);
}
SWIGINTERN Hypothesis *Decoder_hyp(Decoder *self) {
    char const *hyp;
    int best_score, prob;
    hyp = ps_get_hyp(self, &best_score);
    if (hyp)
        prob = ps_get_prob(self);
    return hyp ? new_Hypothesis(hyp, best_score, prob) : NULL;
}
SWIGINTERN FrontEnd *Decoder_get_fe(Decoder *self) {
    return ps_get_fe(self);
}
SWIGINTERN Feature *Decoder_get_feat(Decoder *self) {
    return ps_get_feat(self);
}
SWIGINTERN bool Decoder_get_in_speech(Decoder *self) {
    return ps_get_in_speech(self);
}
SWIGINTERN FsgModel *Decoder_get_fsg(Decoder *self, char const *name) {
    return fsg_model_retain(ps_get_fsg(self, name));
}
SWIGINTERN void Decoder_set_fsg(Decoder *self, char const *name, FsgModel *fsg, int *errcode) {
    *errcode = ps_set_fsg(self, name, fsg);
}
SWIGINTERN void Decoder_set_jsgf_file(Decoder *self, char const *name, char const *path, int *errcode) {
    *errcode = ps_set_jsgf_file(self, name, path);
}
SWIGINTERN void Decoder_set_jsgf_string(Decoder *self, char const *name, char const *jsgf_string, int *errcode) {
    *errcode = ps_set_jsgf_string(self, name, jsgf_string);
}
SWIGINTERN char const *Decoder_get_kws(Decoder *self, char const *name) {
    return ps_get_kws(self, name);
}
SWIGINTERN void Decoder_set_kws(Decoder *self, char const *name, char const *keyfile, int *errcode) {
    *errcode = ps_set_kws(self, name, keyfile);
}
SWIGINTERN void Decoder_set_keyphrase(Decoder *self, char const *name, char const *keyphrase, int *errcode) {
    *errcode = ps_set_keyphrase(self, name, keyphrase);
}
SWIGINTERN void Decoder_set_allphone_file(Decoder *self, char const *name, char const *lmfile, int *errcode) {
    *errcode = ps_set_allphone_file(self, name, lmfile);
}
SWIGINTERN NGramModel *Decoder_get_lm(Decoder *self, char const *name) {
    return ngram_model_retain(ps_get_lm(self, name));
}
SWIGINTERN void Decoder_set_lm(Decoder *self, char const *name, NGramModel *lm, int *errcode) {
    *errcode = ps_set_lm(self, name, lm);
}
SWIGINTERN void Decoder_set_lm_file(Decoder *self, char const *name, char const *path, int *errcode) {
    *errcode = ps_set_lm_file(self, name, path);
}
SWIGINTERN LogMath *Decoder_get_logmath(Decoder *self) {
    return logmath_retain(ps_get_logmath(self));
}
SWIGINTERN void Decoder_set_search(Decoder *self, char const *search_name, int *errcode) {
    *errcode = ps_set_search(self, search_name);
}
SWIGINTERN void Decoder_unset_search(Decoder *self, char const *search_name, int *errcode) {
    *errcode = ps_unset_search(self, search_name);
}
SWIGINTERN char const *Decoder_get_search(Decoder *self) {
    return ps_get_search(self);
}
SWIGINTERN int Decoder_n_frames(Decoder *self) {
    return ps_get_n_frames(self);
}
SWIGINTERN SegmentList *Decoder_seg(Decoder *self) {
    return self;
}
SWIGINTERN NBestList *Decoder_nbest(Decoder *self) {
    return self;
}
SWIGINTERN Lattice *new_Lattice__SWIG_0(char const *path) {
    return ps_lattice_read(NULL, path);
}
SWIGINTERN Lattice *new_Lattice__SWIG_1(Decoder *decoder, char *path) {
    return ps_lattice_read(decoder, path);
}
SWIGINTERN void delete_Lattice(Lattice *self) {
    ps_lattice_free(self);
}
SWIGINTERN void Lattice_write(Lattice *self, char const *path, int *errcode) {
    *errcode = ps_lattice_write(self, path);
}
SWIGINTERN void Lattice_write_htk(Lattice *self, char const *path, int *errcode) {
    *errcode = ps_lattice_write_htk(self, path);
}
SWIGINTERN NBestIterator *NBestList___iter__(NBestList *self) {
    return new_NBestIterator(ps_nbest(self));
}
SWIGINTERN SegmentIterator *SegmentList___iter__(SegmentList *self) {
    return new_SegmentIterator(ps_seg_iter(self));
}

#ifdef __cplusplus
extern "C" {
#endif

    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Hypothesis_hypstr_set(void * jarg1, char * jarg2) {
        Hypothesis *arg1 = (Hypothesis *)0;
        char *arg2 = (char *)0;

        arg1 = (Hypothesis *)jarg1;
        arg2 = (char *)jarg2;
        {
            free(arg1->hypstr);
            if (arg2) {
                arg1->hypstr = (char *)malloc(strlen((const char *)arg2) + 1);
                strcpy((char *)arg1->hypstr, (const char *)arg2);
            }
            else {
                arg1->hypstr = 0;
            }
        }
    }


    SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_Hypothesis_hypstr_get(void * jarg1) {
        char * jresult;
        Hypothesis *arg1 = (Hypothesis *)0;
        char *result = 0;

        arg1 = (Hypothesis *)jarg1;
        result = (char *)((arg1)->hypstr);
        jresult = SWIG_csharp_string_callback((const char *)result);
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Hypothesis_best_score_set(void * jarg1, int jarg2) {
        Hypothesis *arg1 = (Hypothesis *)0;
        int arg2;

        arg1 = (Hypothesis *)jarg1;
        arg2 = (int)jarg2;
        if (arg1) (arg1)->best_score = arg2;
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Hypothesis_best_score_get(void * jarg1) {
        int jresult;
        Hypothesis *arg1 = (Hypothesis *)0;
        int result;

        arg1 = (Hypothesis *)jarg1;
        result = (int)((arg1)->best_score);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Hypothesis_prob_set(void * jarg1, int jarg2) {
        Hypothesis *arg1 = (Hypothesis *)0;
        int arg2;

        arg1 = (Hypothesis *)jarg1;
        arg2 = (int)jarg2;
        if (arg1) (arg1)->prob = arg2;
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Hypothesis_prob_get(void * jarg1) {
        int jresult;
        Hypothesis *arg1 = (Hypothesis *)0;
        int result;

        arg1 = (Hypothesis *)jarg1;
        result = (int)((arg1)->prob);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_Hypothesis(char * jarg1, int jarg2, int jarg3) {
        void * jresult;
        char *arg1 = (char *)0;
        int arg2;
        int arg3;
        Hypothesis *result = 0;

        arg1 = (char *)jarg1;
        arg2 = (int)jarg2;
        arg3 = (int)jarg3;
        result = (Hypothesis *)new_Hypothesis((char const *)arg1, arg2, arg3);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_Hypothesis(void * jarg1) {
        Hypothesis *arg1 = (Hypothesis *)0;

        arg1 = (Hypothesis *)jarg1;
        delete_Hypothesis(arg1);
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Segment_word_set(void * jarg1, char * jarg2) {
        Segment *arg1 = (Segment *)0;
        char *arg2 = (char *)0;

        arg1 = (Segment *)jarg1;
        arg2 = (char *)jarg2;
        {
            free(arg1->word);
            if (arg2) {
                arg1->word = (char *)malloc(strlen((const char *)arg2) + 1);
                strcpy((char *)arg1->word, (const char *)arg2);
            }
            else {
                arg1->word = 0;
            }
        }
    }


    SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_Segment_word_get(void * jarg1) {
        char * jresult;
        Segment *arg1 = (Segment *)0;
        char *result = 0;

        arg1 = (Segment *)jarg1;
        result = (char *)((arg1)->word);
        jresult = SWIG_csharp_string_callback((const char *)result);
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Segment_ascore_set(void * jarg1, int jarg2) {
        Segment *arg1 = (Segment *)0;
        int arg2;

        arg1 = (Segment *)jarg1;
        arg2 = (int)jarg2;
        if (arg1) (arg1)->ascore = arg2;
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Segment_ascore_get(void * jarg1) {
        int jresult;
        Segment *arg1 = (Segment *)0;
        int result;

        arg1 = (Segment *)jarg1;
        result = (int)((arg1)->ascore);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Segment_lscore_set(void * jarg1, int jarg2) {
        Segment *arg1 = (Segment *)0;
        int arg2;

        arg1 = (Segment *)jarg1;
        arg2 = (int)jarg2;
        if (arg1) (arg1)->lscore = arg2;
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Segment_lscore_get(void * jarg1) {
        int jresult;
        Segment *arg1 = (Segment *)0;
        int result;

        arg1 = (Segment *)jarg1;
        result = (int)((arg1)->lscore);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Segment_lback_set(void * jarg1, int jarg2) {
        Segment *arg1 = (Segment *)0;
        int arg2;

        arg1 = (Segment *)jarg1;
        arg2 = (int)jarg2;
        if (arg1) (arg1)->lback = arg2;
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Segment_lback_get(void * jarg1) {
        int jresult;
        Segment *arg1 = (Segment *)0;
        int result;

        arg1 = (Segment *)jarg1;
        result = (int)((arg1)->lback);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Segment_prob_set(void * jarg1, int jarg2) {
        Segment *arg1 = (Segment *)0;
        int arg2;

        arg1 = (Segment *)jarg1;
        arg2 = (int)jarg2;
        if (arg1) (arg1)->prob = arg2;
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Segment_prob_get(void * jarg1) {
        int jresult;
        Segment *arg1 = (Segment *)0;
        int result;

        arg1 = (Segment *)jarg1;
        result = (int)((arg1)->prob);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Segment_start_frame_set(void * jarg1, int jarg2) {
        Segment *arg1 = (Segment *)0;
        int arg2;

        arg1 = (Segment *)jarg1;
        arg2 = (int)jarg2;
        if (arg1) (arg1)->start_frame = arg2;
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Segment_start_frame_get(void * jarg1) {
        int jresult;
        Segment *arg1 = (Segment *)0;
        int result;

        arg1 = (Segment *)jarg1;
        result = (int)((arg1)->start_frame);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Segment_end_frame_set(void * jarg1, int jarg2) {
        Segment *arg1 = (Segment *)0;
        int arg2;

        arg1 = (Segment *)jarg1;
        arg2 = (int)jarg2;
        if (arg1) (arg1)->end_frame = arg2;
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Segment_end_frame_get(void * jarg1) {
        int jresult;
        Segment *arg1 = (Segment *)0;
        int result;

        arg1 = (Segment *)jarg1;
        result = (int)((arg1)->end_frame);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Segment_fromIter(void * jarg1) {
        void * jresult;
        void *arg1 = (void *)0;
        Segment *result = 0;

        arg1 = (void *)jarg1;
        result = (Segment *)Segment_fromIter(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_Segment(void * jarg1) {
        Segment *arg1 = (Segment *)0;

        arg1 = (Segment *)jarg1;
        delete_Segment(arg1);
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_Segment() {
        void * jresult;
        Segment *result = 0;

        result = (Segment *)calloc(1, sizeof(Segment));
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_NBest_hypstr_set(void * jarg1, char * jarg2) {
        NBest *arg1 = (NBest *)0;
        char *arg2 = (char *)0;

        arg1 = (NBest *)jarg1;
        arg2 = (char *)jarg2;
        {
            free(arg1->hypstr);
            if (arg2) {
                arg1->hypstr = (char *)malloc(strlen((const char *)arg2) + 1);
                strcpy((char *)arg1->hypstr, (const char *)arg2);
            }
            else {
                arg1->hypstr = 0;
            }
        }
    }


    SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_NBest_hypstr_get(void * jarg1) {
        char * jresult;
        NBest *arg1 = (NBest *)0;
        char *result = 0;

        arg1 = (NBest *)jarg1;
        result = (char *)((arg1)->hypstr);
        jresult = SWIG_csharp_string_callback((const char *)result);
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_NBest_score_set(void * jarg1, int jarg2) {
        NBest *arg1 = (NBest *)0;
        int arg2;

        arg1 = (NBest *)jarg1;
        arg2 = (int)jarg2;
        if (arg1) (arg1)->score = arg2;
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_NBest_score_get(void * jarg1) {
        int jresult;
        NBest *arg1 = (NBest *)0;
        int result;

        arg1 = (NBest *)jarg1;
        result = (int)((arg1)->score);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NBest_fromIter(void * jarg1) {
        void * jresult;
        void *arg1 = (void *)0;
        NBest *result = 0;

        arg1 = (void *)jarg1;
        result = (NBest *)NBest_fromIter(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NBest_hyp(void * jarg1) {
        void * jresult;
        NBest *arg1 = (NBest *)0;
        Hypothesis *result = 0;

        arg1 = (NBest *)jarg1;
        result = (Hypothesis *)NBest_hyp(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_NBest(void * jarg1) {
        NBest *arg1 = (NBest *)0;

        arg1 = (NBest *)jarg1;
        delete_NBest(arg1);
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_NBest() {
        void * jresult;
        NBest *result = 0;

        result = (NBest *)calloc(1, sizeof(NBest));
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_SegmentIterator_ptr_set(void * jarg1, void * jarg2) {
        SegmentIterator *arg1 = (SegmentIterator *)0;
        ps_seg_t *arg2 = (ps_seg_t *)0;

        arg1 = (SegmentIterator *)jarg1;
        arg2 = (ps_seg_t *)jarg2;
        if (arg1) (arg1)->ptr = arg2;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_SegmentIterator_ptr_get(void * jarg1) {
        void * jresult;
        SegmentIterator *arg1 = (SegmentIterator *)0;
        ps_seg_t *result = 0;

        arg1 = (SegmentIterator *)jarg1;
        result = (ps_seg_t *)((arg1)->ptr);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_SegmentIterator(void * jarg1) {
        void * jresult;
        ps_seg_t *arg1 = (ps_seg_t *)0;
        SegmentIterator *result = 0;

        arg1 = (ps_seg_t *)jarg1;
        result = (SegmentIterator *)new_SegmentIterator(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_SegmentIterator(void * jarg1) {
        SegmentIterator *arg1 = (SegmentIterator *)0;

        arg1 = (SegmentIterator *)jarg1;
        delete_SegmentIterator(arg1);
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_NBestIterator_ptr_set(void * jarg1, void * jarg2) {
        NBestIterator *arg1 = (NBestIterator *)0;
        ps_nbest_t *arg2 = (ps_nbest_t *)0;

        arg1 = (NBestIterator *)jarg1;
        arg2 = (ps_nbest_t *)jarg2;
        if (arg1) (arg1)->ptr = arg2;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NBestIterator_ptr_get(void * jarg1) {
        void * jresult;
        NBestIterator *arg1 = (NBestIterator *)0;
        ps_nbest_t *result = 0;

        arg1 = (NBestIterator *)jarg1;
        result = (ps_nbest_t *)((arg1)->ptr);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_NBestIterator(void * jarg1) {
        void * jresult;
        ps_nbest_t *arg1 = (ps_nbest_t *)0;
        NBestIterator *result = 0;

        arg1 = (ps_nbest_t *)jarg1;
        result = (NBestIterator *)new_NBestIterator(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_NBestIterator(void * jarg1) {
        NBestIterator *arg1 = (NBestIterator *)0;

        arg1 = (NBestIterator *)jarg1;
        delete_NBestIterator(arg1);
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_Decoder__SWIG_0() {
        void * jresult;
        int *arg1 = (int *)0;
        Decoder *result = 0;

        int errcode;
        arg1 = &errcode;
        result = (Decoder *)new_Decoder__SWIG_0(arg1);
        jresult = (void *)result;
        {
            if (*arg1 < 0) {
                char buf[64];
                sprintf(buf, "new_Decoder returned %d", *arg1);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return 0;
                };
            }
        }
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_Decoder__SWIG_1(void * jarg1) {
        void * jresult;
        Config *arg1 = (Config *)0;
        int *arg2 = (int *)0;
        Decoder *result = 0;

        int errcode;
        arg2 = &errcode;
        arg1 = (Config *)jarg1;
        result = (Decoder *)new_Decoder__SWIG_1(arg1, arg2);
        jresult = (void *)result;
        {
            if (*arg2 < 0) {
                char buf[64];
                sprintf(buf, "new_Decoder returned %d", *arg2);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return 0;
                };
            }
        }
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_Decoder(void * jarg1) {
        Decoder *arg1 = (Decoder *)0;

        arg1 = (Decoder *)jarg1;
        delete_Decoder(arg1);
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_reinit(void * jarg1, void * jarg2) {
        Decoder *arg1 = (Decoder *)0;
        Config *arg2 = (Config *)0;
        int *arg3 = (int *)0;

        int errcode;
        arg3 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (Config *)jarg2;
        Decoder_reinit(arg1, arg2, arg3);
        {
            if (*arg3 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_reinit returned %d", *arg3);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_load_dict(void * jarg1, char * jarg2, char * jarg3, char * jarg4) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *arg3 = (char *)0;
        char *arg4 = (char *)0;
        int *arg5 = (int *)0;

        int errcode;
        arg5 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (char *)jarg3;
        arg4 = (char *)jarg4;
        Decoder_load_dict(arg1, (char const *)arg2, (char const *)arg3, (char const *)arg4, arg5);
        {
            if (*arg5 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_load_dict returned %d", *arg5);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_save_dict(void * jarg1, char * jarg2, char * jarg3) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *arg3 = (char *)0;
        int *arg4 = (int *)0;

        int errcode;
        arg4 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (char *)jarg3;
        Decoder_save_dict(arg1, (char const *)arg2, (char const *)arg3, arg4);
        {
            if (*arg4 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_save_dict returned %d", *arg4);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_add_word(void * jarg1, char * jarg2, char * jarg3, int jarg4) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *arg3 = (char *)0;
        int arg4;
        int *arg5 = (int *)0;

        int errcode;
        arg5 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (char *)jarg3;
        arg4 = (int)jarg4;
        Decoder_add_word(arg1, (char const *)arg2, (char const *)arg3, arg4, arg5);
        {
            if (*arg5 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_add_word returned %d", *arg5);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_lookup_word(void * jarg1, char * jarg2) {
        char * jresult;
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *result = 0;

        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        result = (char *)Decoder_lookup_word(arg1, (char const *)arg2);
        jresult = SWIG_csharp_string_callback((const char *)result);
        free(result);
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_get_lattice(void * jarg1) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        Lattice *result = 0;

        arg1 = (Decoder *)jarg1;
        result = (Lattice *)Decoder_get_lattice(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_get_config(void * jarg1) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        Config *result = 0;

        arg1 = (Decoder *)jarg1;
        result = (Config *)Decoder_get_config(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_default_config() {
        void * jresult;
        Config *result = 0;

        result = (Config *)Decoder_default_config();
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_file_config(char * jarg1) {
        void * jresult;
        char *arg1 = (char *)0;
        Config *result = 0;

        arg1 = (char *)jarg1;
        result = (Config *)Decoder_file_config((char const *)arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_start_stream(void * jarg1) {
        Decoder *arg1 = (Decoder *)0;
        int *arg2 = (int *)0;

        int errcode;
        arg2 = &errcode;
        arg1 = (Decoder *)jarg1;
        Decoder_start_stream(arg1, arg2);
        {
            if (*arg2 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_start_stream returned %d", *arg2);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_start_utt(void * jarg1) {
        Decoder *arg1 = (Decoder *)0;
        int *arg2 = (int *)0;

        int errcode;
        arg2 = &errcode;
        arg1 = (Decoder *)jarg1;
        Decoder_start_utt(arg1, arg2);
        {
            if (*arg2 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_start_utt returned %d", *arg2);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_end_utt(void * jarg1) {
        Decoder *arg1 = (Decoder *)0;
        int *arg2 = (int *)0;

        int errcode;
        arg2 = &errcode;
        arg1 = (Decoder *)jarg1;
        Decoder_end_utt(arg1, arg2);
        {
            if (*arg2 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_end_utt returned %d", *arg2);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Decoder_process_raw(void * jarg1, void * jarg2, int jarg3, unsigned int jarg4, unsigned int jarg5) {
        int jresult;
        Decoder *arg1 = (Decoder *)0;
        unsigned char *arg2 = (unsigned char *)0;
        int arg3;
        bool arg4;
        bool arg5;
        int *arg6 = (int *)0;
        int result;

        int errcode;
        arg6 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (unsigned char *)jarg2;
        arg3 = (int)jarg3;
        arg4 = jarg4 ? true : false;
        arg5 = jarg5 ? true : false;
        result = (int)Decoder_process_raw(arg1, (unsigned char const *)arg2, arg3, arg4, arg5, arg6);
        jresult = result;
        {
            if (*arg6 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_process_raw returned %d", *arg6);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return 0;
                };
            }
        }
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_hyp(void * jarg1) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        Hypothesis *result = 0;

        arg1 = (Decoder *)jarg1;
        result = (Hypothesis *)Decoder_hyp(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_get_fe(void * jarg1) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        FrontEnd *result = 0;

        arg1 = (Decoder *)jarg1;
        result = (FrontEnd *)Decoder_get_fe(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_get_feat(void * jarg1) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        Feature *result = 0;

        arg1 = (Decoder *)jarg1;
        result = (Feature *)Decoder_get_feat(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Pocketsphinx_Decoder_get_in_speech(void * jarg1) {
        unsigned int jresult;
        Decoder *arg1 = (Decoder *)0;
        bool result;

        arg1 = (Decoder *)jarg1;
        result = (bool)Decoder_get_in_speech(arg1);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_get_fsg(void * jarg1, char * jarg2) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        FsgModel *result = 0;

        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        result = (FsgModel *)Decoder_get_fsg(arg1, (char const *)arg2);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_set_fsg(void * jarg1, char * jarg2, void * jarg3) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        FsgModel *arg3 = (FsgModel *)0;
        int *arg4 = (int *)0;

        int errcode;
        arg4 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (FsgModel *)jarg3;
        Decoder_set_fsg(arg1, (char const *)arg2, arg3, arg4);
        {
            if (*arg4 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_set_fsg returned %d", *arg4);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_set_jsgf_file(void * jarg1, char * jarg2, char * jarg3) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *arg3 = (char *)0;
        int *arg4 = (int *)0;

        int errcode;
        arg4 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (char *)jarg3;
        Decoder_set_jsgf_file(arg1, (char const *)arg2, (char const *)arg3, arg4);
        {
            if (*arg4 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_set_jsgf_file returned %d", *arg4);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_set_jsgf_string(void * jarg1, char * jarg2, char * jarg3) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *arg3 = (char *)0;
        int *arg4 = (int *)0;

        int errcode;
        arg4 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (char *)jarg3;
        Decoder_set_jsgf_string(arg1, (char const *)arg2, (char const *)arg3, arg4);
        {
            if (*arg4 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_set_jsgf_string returned %d", *arg4);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_get_kws(void * jarg1, char * jarg2) {
        char * jresult;
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *result = 0;

        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        result = (char *)Decoder_get_kws(arg1, (char const *)arg2);
        jresult = SWIG_csharp_string_callback((const char *)result);
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_set_kws(void * jarg1, char * jarg2, char * jarg3) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *arg3 = (char *)0;
        int *arg4 = (int *)0;

        int errcode;
        arg4 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (char *)jarg3;
        Decoder_set_kws(arg1, (char const *)arg2, (char const *)arg3, arg4);
        {
            if (*arg4 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_set_kws returned %d", *arg4);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_set_keyphrase(void * jarg1, char * jarg2, char * jarg3) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *arg3 = (char *)0;
        int *arg4 = (int *)0;

        int errcode;
        arg4 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (char *)jarg3;
        Decoder_set_keyphrase(arg1, (char const *)arg2, (char const *)arg3, arg4);
        {
            if (*arg4 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_set_keyphrase returned %d", *arg4);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_set_allphone_file(void * jarg1, char * jarg2, char * jarg3) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *arg3 = (char *)0;
        int *arg4 = (int *)0;

        int errcode;
        arg4 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (char *)jarg3;
        Decoder_set_allphone_file(arg1, (char const *)arg2, (char const *)arg3, arg4);
        {
            if (*arg4 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_set_allphone_file returned %d", *arg4);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_get_lm(void * jarg1, char * jarg2) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        NGramModel *result = 0;

        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        result = (NGramModel *)Decoder_get_lm(arg1, (char const *)arg2);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_set_lm(void * jarg1, char * jarg2, void * jarg3) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        NGramModel *arg3 = (NGramModel *)0;
        int *arg4 = (int *)0;

        int errcode;
        arg4 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (NGramModel *)jarg3;
        Decoder_set_lm(arg1, (char const *)arg2, arg3, arg4);
        {
            if (*arg4 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_set_lm returned %d", *arg4);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_set_lm_file(void * jarg1, char * jarg2, char * jarg3) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        char *arg3 = (char *)0;
        int *arg4 = (int *)0;

        int errcode;
        arg4 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        arg3 = (char *)jarg3;
        Decoder_set_lm_file(arg1, (char const *)arg2, (char const *)arg3, arg4);
        {
            if (*arg4 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_set_lm_file returned %d", *arg4);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_get_logmath(void * jarg1) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        LogMath *result = 0;

        arg1 = (Decoder *)jarg1;
        result = (LogMath *)Decoder_get_logmath(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_set_search(void * jarg1, char * jarg2) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        int *arg3 = (int *)0;

        int errcode;
        arg3 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        Decoder_set_search(arg1, (char const *)arg2, arg3);
        {
            if (*arg3 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_set_search returned %d", *arg3);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Decoder_unset_search(void * jarg1, char * jarg2) {
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        int *arg3 = (int *)0;

        int errcode;
        arg3 = &errcode;
        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        Decoder_unset_search(arg1, (char const *)arg2, arg3);
        {
            if (*arg3 < 0) {
                char buf[64];
                sprintf(buf, "Decoder_unset_search returned %d", *arg3);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_get_search(void * jarg1) {
        char * jresult;
        Decoder *arg1 = (Decoder *)0;
        char *result = 0;

        arg1 = (Decoder *)jarg1;
        result = (char *)Decoder_get_search(arg1);
        jresult = SWIG_csharp_string_callback((const char *)result);
        return jresult;
    }


    SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Decoder_n_frames(void * jarg1) {
        int jresult;
        Decoder *arg1 = (Decoder *)0;
        int result;

        arg1 = (Decoder *)jarg1;
        result = (int)Decoder_n_frames(arg1);
        jresult = result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_seg(void * jarg1) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        SegmentList *result = 0;

        arg1 = (Decoder *)jarg1;
        result = (SegmentList *)Decoder_seg(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Decoder_nbest(void * jarg1) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        NBestList *result = 0;

        arg1 = (Decoder *)jarg1;
        result = (NBestList *)Decoder_nbest(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_Lattice__SWIG_0(char * jarg1) {
        void * jresult;
        char *arg1 = (char *)0;
        Lattice *result = 0;

        arg1 = (char *)jarg1;
        result = (Lattice *)new_Lattice__SWIG_0((char const *)arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_Lattice__SWIG_1(void * jarg1, char * jarg2) {
        void * jresult;
        Decoder *arg1 = (Decoder *)0;
        char *arg2 = (char *)0;
        Lattice *result = 0;

        arg1 = (Decoder *)jarg1;
        arg2 = (char *)jarg2;
        result = (Lattice *)new_Lattice__SWIG_1(arg1, arg2);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_Lattice(void * jarg1) {
        Lattice *arg1 = (Lattice *)0;

        arg1 = (Lattice *)jarg1;
        delete_Lattice(arg1);
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Lattice_write(void * jarg1, char * jarg2) {
        Lattice *arg1 = (Lattice *)0;
        char *arg2 = (char *)0;
        int *arg3 = (int *)0;

        int errcode;
        arg3 = &errcode;
        arg1 = (Lattice *)jarg1;
        arg2 = (char *)jarg2;
        Lattice_write(arg1, (char const *)arg2, arg3);
        {
            if (*arg3 < 0) {
                char buf[64];
                sprintf(buf, "Lattice_write returned %d", *arg3);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Lattice_write_htk(void * jarg1, char * jarg2) {
        Lattice *arg1 = (Lattice *)0;
        char *arg2 = (char *)0;
        int *arg3 = (int *)0;

        int errcode;
        arg3 = &errcode;
        arg1 = (Lattice *)jarg1;
        arg2 = (char *)jarg2;
        Lattice_write_htk(arg1, (char const *)arg2, arg3);
        {
            if (*arg3 < 0) {
                char buf[64];
                sprintf(buf, "Lattice_write_htk returned %d", *arg3);
                {
                    SWIG_CSharpException(SWIG_RuntimeError, buf); return;
                };
            }
        }
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NBestList___iter__(void * jarg1) {
        void * jresult;
        NBestList *arg1 = (NBestList *)0;
        NBestIterator *result = 0;

        arg1 = (NBestList *)jarg1;
        result = (NBestIterator *)NBestList___iter__(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_NBestList(void * jarg1) {
        NBestList *arg1 = (NBestList *)0;

        arg1 = (NBestList *)jarg1;
        free((char *)arg1);
    }


    SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_SegmentList___iter__(void * jarg1) {
        void * jresult;
        SegmentList *arg1 = (SegmentList *)0;
        SegmentIterator *result = 0;

        arg1 = (SegmentList *)jarg1;
        result = (SegmentIterator *)SegmentList___iter__(arg1);
        jresult = (void *)result;
        return jresult;
    }


    SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_SegmentList(void * jarg1) {
        SegmentList *arg1 = (SegmentList *)0;

        arg1 = (SegmentList *)jarg1;
        free((char *)arg1);
    }


#ifdef __cplusplus
}
#endif

