/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef __cplusplus
typedef int bool;
#define true 1
#define false 0
#endif

#include <sphinxbase/cmd_ln.h>
#include <sphinxbase/err.h>
#include <sphinxbase/fe.h>
#include <sphinxbase/feat.h>
#include <sphinxbase/jsgf.h>
#include <sphinxbase/ngram_model.h>

typedef cmd_ln_t Config;
typedef jsgf_t Jsgf;
typedef jsgf_rule_t JsgfRule;
typedef feat_t Feature;
typedef fe_t FrontEnd;
typedef fsg_model_t FsgModel;
typedef logmath_t LogMath;
typedef ngram_model_t NGramModel;
typedef ngram_model_t NGramModelSet;



#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_sphinxbase(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_sphinxbase(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_sphinxbase(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13




SWIGINTERN void SWIG_CSharpException(int code, const char *msg) {
  if (code == SWIG_ValueError) {
    SWIG_CSharpExceptionArgumentCodes exception_code = SWIG_CSharpArgumentOutOfRangeException;
    SWIG_CSharpSetPendingExceptionArgument(exception_code, msg, 0);
  } else {
    SWIG_CSharpExceptionCodes exception_code = SWIG_CSharpApplicationException;
    switch(code) {
    case SWIG_MemoryError:
      exception_code = SWIG_CSharpOutOfMemoryException;
      break;
    case SWIG_IndexError:
      exception_code = SWIG_CSharpIndexOutOfRangeException;
      break;
    case SWIG_DivisionByZero:
      exception_code = SWIG_CSharpDivideByZeroException;
      break;
    case SWIG_IOError:
      exception_code = SWIG_CSharpIOException;
      break;
    case SWIG_OverflowError:
      exception_code = SWIG_CSharpOverflowException;
      break;
    case SWIG_RuntimeError:
    case SWIG_TypeError:
    case SWIG_SyntaxError:
    case SWIG_SystemError:
    case SWIG_UnknownError:
    default:
      exception_code = SWIG_CSharpApplicationException;
      break;
    }
    SWIG_CSharpSetPendingException(exception_code, msg);
  }
}

SWIGINTERN void delete_Config(Config *self){
        cmd_ln_free_r(self);
    }
SWIGINTERN void Config_set_boolean(Config *self,char const *key,bool val){
        cmd_ln_set_boolean_r(self, key, val);
    }
SWIGINTERN void Config_set_int(Config *self,char const *key,int val){
        cmd_ln_set_int_r(self, key, val);
    }
SWIGINTERN void Config_set_float(Config *self,char const *key,double val){
        cmd_ln_set_float_r(self, key, val);
    }
SWIGINTERN void Config_set_string(Config *self,char const *key,char const *val){
        cmd_ln_set_str_r(self, key, val);
    }
SWIGINTERN void Config_set_string_extra(Config *self,char const *key,char const *val){
        cmd_ln_set_str_extra_r(self, key, val);
    }
SWIGINTERN bool Config_exists(Config *self,char const *key){
        return cmd_ln_exists_r(self, key);
    }
SWIGINTERN bool Config_get_boolean(Config *self,char const *key){
        return cmd_ln_boolean_r(self, key);
    }
SWIGINTERN int Config_get_int(Config *self,char const *key){
        return cmd_ln_int_r(self, key);
    }
SWIGINTERN double Config_get_float(Config *self,char const *key){
        return cmd_ln_float_r(self, key);
    }
SWIGINTERN char const *Config_get_string(Config *self,char const *key){
        return cmd_ln_str_r(self, key);
    }
SWIGINTERN FrontEnd *new_FrontEnd(fe_t *ptr){
        return ptr;
    }
SWIGINTERN void delete_FrontEnd(FrontEnd *self){
        fe_free(self);
    }
SWIGINTERN int FrontEnd_output_size(FrontEnd *self){
        return fe_get_output_size(self);
    }
SWIGINTERN void FrontEnd_start_utt(FrontEnd *self,int *errcode){
        *errcode = fe_start_utt(self);
    }
SWIGINTERN int32 FrontEnd_process_utt(FrontEnd *self,int16 const *spch,size_t nsamps,mfcc_t ***cep_block,int *errcode){
        int32 nframes;
        *errcode = fe_process_utt(self, spch, nsamps, cep_block, &nframes);
        return nframes;
    }
SWIGINTERN int32 FrontEnd_end_utt(FrontEnd *self,mfcc_t *out_cepvector,int *errcode){
        int32 nframes;
        *errcode = fe_end_utt(self, out_cepvector, &nframes);
        return nframes;
    }
SWIGINTERN Feature *new_Feature(feat_t *ptr){
      return ptr;
    }
SWIGINTERN void delete_Feature(Feature *self){
        feat_free(self);
    }
SWIGINTERN FsgModel *new_FsgModel__SWIG_0(char const *name,LogMath *logmath,float lw,int32 n){
	return fsg_model_init(name, logmath, lw, n);
    }
SWIGINTERN FsgModel *new_FsgModel__SWIG_1(fsg_model_t *ptr){
        return ptr;
    }
SWIGINTERN FsgModel *new_FsgModel__SWIG_2(char const *path,LogMath *logmath,float lw){
        return fsg_model_readfile(path, logmath, lw);
    }
SWIGINTERN void delete_FsgModel(FsgModel *self){
        fsg_model_free(self);
    }
SWIGINTERN int FsgModel_word_id(FsgModel *self,char const *word){
        return fsg_model_word_id(self, word);
    }
SWIGINTERN int FsgModel_word_add(FsgModel *self,char const *word){
        return fsg_model_word_add(self, word);
    }
SWIGINTERN void FsgModel_trans_add(FsgModel *self,int32 src,int32 dst,int32 logp,int32 wid){
        fsg_model_trans_add(self, src, dst, logp, wid);
    }
SWIGINTERN int32 FsgModel_null_trans_add(FsgModel *self,int32 src,int32 dst,int32 logp){
        return fsg_model_null_trans_add(self, src, dst, logp);
    }
SWIGINTERN int32 FsgModel_tag_trans_add(FsgModel *self,int32 src,int32 dst,int32 logp,int32 wid){
        return fsg_model_tag_trans_add(self, src, dst, logp, wid);
    }
SWIGINTERN int FsgModel_add_silence(FsgModel *self,char const *silword,int32 state,float silprob){
        return fsg_model_add_silence(self, silword, state, silprob); 
    }
SWIGINTERN int FsgModel_add_alt(FsgModel *self,char const *baseword,char const *altword){
        return fsg_model_add_alt(self, baseword, altword);
    }
SWIGINTERN void FsgModel_writefile(FsgModel *self,char const *path){
        fsg_model_writefile(self, path);
    }
SWIGINTERN JsgfRule *new_JsgfRule(void){
    return NULL;
  }
SWIGINTERN void delete_JsgfRule(JsgfRule *self){
  }
SWIGINTERN JsgfRule *JsgfRule_fromIter(jsgf_rule_iter_t *itor){
    return jsgf_rule_iter_rule(itor);
  }
SWIGINTERN char const *JsgfRule_name(JsgfRule *self){
    return jsgf_rule_name(self);
  }
SWIGINTERN bool JsgfRule_public(JsgfRule *self){
    return jsgf_rule_public(self);
  }
SWIGINTERN NGramModel *NGramModel_fromIter(ngram_model_set_iter_t *itor){
        const char *name;
	return ngram_model_set_iter_model(itor, &name);
    }
SWIGINTERN NGramModel *new_NGramModel__SWIG_0(char const *path){
        logmath_t *lmath = logmath_init(1.0001, 0, 0);
        ngram_model_t * model = ngram_model_read(NULL, path, NGRAM_AUTO, lmath);
        logmath_free(lmath);
        return model;
    }
SWIGINTERN NGramModel *new_NGramModel__SWIG_1(Config *config,LogMath *logmath,char const *path){
        return ngram_model_read(config, path, NGRAM_AUTO, logmath);
    }
SWIGINTERN void delete_NGramModel(NGramModel *self){
        ngram_model_free(self);
    }
SWIGINTERN void NGramModel_write(NGramModel *self,char const *path,ngram_file_type_t ftype,int *errcode){
        *errcode = ngram_model_write(self, path, ftype);
    }
SWIGINTERN ngram_file_type_t NGramModel_str_to_type(NGramModel *self,char const *str){
        return ngram_str_to_type(str);
    }
SWIGINTERN char const *NGramModel_type_to_str(NGramModel *self,int type){
        return ngram_type_to_str(type);
    }
SWIGINTERN void NGramModel_casefold(NGramModel *self,int kase,int *errcode){
        *errcode = ngram_model_casefold(self, kase);
    }
SWIGINTERN int32 NGramModel_size(NGramModel *self){
        return ngram_model_get_size(self);
    }
SWIGINTERN int32 NGramModel_add_word(NGramModel *self,char const *word,float32 weight){
        return ngram_model_add_word(self, word, weight);
    }
SWIGINTERN int32 NGramModel_prob(NGramModel *self,size_t n,char const *const *ptr){
        return ngram_prob(self, ptr, n);
    }
SWIGINTERN LogMath *new_LogMath__SWIG_0(void){
	return logmath_init(1.0001f, 0, 0);
    }
SWIGINTERN LogMath *new_LogMath__SWIG_1(logmath_t *ptr){
        return ptr;
    }
SWIGINTERN void delete_LogMath(LogMath *self){
        logmath_free(self);
    }
SWIGINTERN float64 LogMath_exp(LogMath *self,int prob){
        return logmath_exp(self, prob);
    }

typedef struct {
  ngram_model_set_iter_t *ptr;
} NGramModelSetIterator;

SWIGINTERN NGramModelSetIterator *new_NGramModelSetIterator(ngram_model_set_iter_t *ptr){
    NGramModelSetIterator *iter = (NGramModelSetIterator *)ckd_malloc(sizeof *iter);
    iter->ptr = ptr;
    return iter;
  }
SWIGINTERN void delete_NGramModelSetIterator(NGramModelSetIterator *self){
    if (self->ptr)
	ngram_model_set_iter_free(self->ptr);
    ckd_free(self);
  }

typedef struct {
  jsgf_rule_iter_t *ptr;
} JsgfIterator;

SWIGINTERN JsgfIterator *new_JsgfIterator(jsgf_rule_iter_t *ptr){
    JsgfIterator *iter = (JsgfIterator *)ckd_malloc(sizeof *iter);
    iter->ptr = ptr;
    return iter;
  }
SWIGINTERN void delete_JsgfIterator(JsgfIterator *self){
    if (self->ptr)
	jsgf_rule_iter_free(self->ptr);
    ckd_free(self);
  }
SWIGINTERN NGramModelSetIterator *NGramModelSet___iter__(NGramModelSet *self){
    return new_NGramModelSetIterator(ngram_model_set_iter(self));
  }
SWIGINTERN NGramModelSet *new_NGramModelSet(Config *config,LogMath *logmath,char const *path){
        return ngram_model_set_read(config, path, logmath);
    }
SWIGINTERN void delete_NGramModelSet(NGramModelSet *self){
        ngram_model_free(self);
    }
SWIGINTERN int32 NGramModelSet_count(NGramModelSet *self){
        return ngram_model_set_count(self);
    }
SWIGINTERN NGramModel *NGramModelSet_add(NGramModelSet *self,NGramModel *model,char const *name,float weight,bool reuse_widmap){
        return ngram_model_set_add(self, model, name, weight, reuse_widmap);
    }
SWIGINTERN NGramModel *NGramModelSet_select(NGramModelSet *self,char const *name){
        return ngram_model_set_select(self, name);
    }
SWIGINTERN NGramModel *NGramModelSet_lookup(NGramModelSet *self,char const *name){
        return ngram_model_set_lookup(self, name);
    }
SWIGINTERN char const *NGramModelSet_current(NGramModelSet *self){
        return ngram_model_set_current(self);
    }
SWIGINTERN JsgfIterator *Jsgf___iter__(Jsgf *self){
    return new_JsgfIterator(jsgf_rule_iter(self));
  }
SWIGINTERN Jsgf *new_Jsgf(char const *path){
    return jsgf_parse_file(path, NULL);
  }
SWIGINTERN void delete_Jsgf(Jsgf *self){
    jsgf_grammar_free(self);
  }
SWIGINTERN char const *Jsgf_name(Jsgf *self){
    return jsgf_grammar_name(self);
  }
SWIGINTERN JsgfRule *Jsgf_get_rule(Jsgf *self,char const *name){
    return jsgf_get_rule(self, name);
  }
SWIGINTERN FsgModel *Jsgf_build_fsg(Jsgf *self,JsgfRule *rule,LogMath *logmath,float lw){
    return jsgf_build_fsg(self, rule, logmath, lw);
  }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_Config(void * jarg1) {
  Config *arg1 = (Config *) 0 ;
  
  arg1 = (Config *)jarg1; 
  delete_Config(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Config_set_boolean(void * jarg1, char * jarg2, unsigned int jarg3) {
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  
  arg1 = (Config *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = jarg3 ? true : false; 
  Config_set_boolean(arg1,(char const *)arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Config_set_int(void * jarg1, char * jarg2, int jarg3) {
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  
  arg1 = (Config *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int)jarg3; 
  Config_set_int(arg1,(char const *)arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Config_set_float(void * jarg1, char * jarg2, double jarg3) {
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  double arg3 ;
  
  arg1 = (Config *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (double)jarg3; 
  Config_set_float(arg1,(char const *)arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Config_set_string(void * jarg1, char * jarg2, char * jarg3) {
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  
  arg1 = (Config *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  Config_set_string(arg1,(char const *)arg2,(char const *)arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_Config_set_string_extra(void * jarg1, char * jarg2, char * jarg3) {
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  
  arg1 = (Config *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  Config_set_string_extra(arg1,(char const *)arg2,(char const *)arg3);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Pocketsphinx_Config_exists(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  arg1 = (Config *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (bool)Config_exists(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Pocketsphinx_Config_get_boolean(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  arg1 = (Config *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (bool)Config_get_boolean(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_Config_get_int(void * jarg1, char * jarg2) {
  int jresult ;
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (Config *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)Config_get_int(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_Pocketsphinx_Config_get_float(void * jarg1, char * jarg2) {
  double jresult ;
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  double result;
  
  arg1 = (Config *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (double)Config_get_float(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_Config_get_string(void * jarg1, char * jarg2) {
  char * jresult ;
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (Config *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (char *)Config_get_string(arg1,(char const *)arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_FrontEnd(void * jarg1) {
  void * jresult ;
  fe_t *arg1 = (fe_t *) 0 ;
  FrontEnd *result = 0 ;
  
  arg1 = (fe_t *)jarg1; 
  result = (FrontEnd *)new_FrontEnd(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_FrontEnd(void * jarg1) {
  FrontEnd *arg1 = (FrontEnd *) 0 ;
  
  arg1 = (FrontEnd *)jarg1; 
  delete_FrontEnd(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_FrontEnd_output_size(void * jarg1) {
  int jresult ;
  FrontEnd *arg1 = (FrontEnd *) 0 ;
  int result;
  
  arg1 = (FrontEnd *)jarg1; 
  result = (int)FrontEnd_output_size(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_FrontEnd_start_utt(void * jarg1) {
  FrontEnd *arg1 = (FrontEnd *) 0 ;
  int *arg2 = (int *) 0 ;
  
  int errcode;
  arg2 = &errcode;
  arg1 = (FrontEnd *)jarg1; 
  FrontEnd_start_utt(arg1,arg2);
  {
    if (*arg2 < 0) {
      char buf[64];
      sprintf(buf, "FrontEnd_start_utt returned %d", *arg2);
      {
        SWIG_CSharpException(SWIG_RuntimeError, buf); return ; 
      };
    }
  }
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_FrontEnd_process_utt(void * jarg1, void * jarg2, unsigned long jarg3, void * jarg4) {
  int jresult ;
  FrontEnd *arg1 = (FrontEnd *) 0 ;
  int16 *arg2 = (int16 *) 0 ;
  size_t arg3 ;
  mfcc_t ***arg4 = (mfcc_t ***) 0 ;
  int *arg5 = (int *) 0 ;
  int32 result;
  
  int errcode;
  arg5 = &errcode;
  arg1 = (FrontEnd *)jarg1; 
  arg2 = (int16 *)jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (mfcc_t ***)jarg4; 
  result = FrontEnd_process_utt(arg1,(int16 const *)arg2,arg3,arg4,arg5);
  jresult = result; 
  {
    if (*arg5 < 0) {
      char buf[64];
      sprintf(buf, "FrontEnd_process_utt returned %d", *arg5);
      {
        SWIG_CSharpException(SWIG_RuntimeError, buf); return 0; 
      };
    }
  }
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_FrontEnd_end_utt(void * jarg1, void * jarg2) {
  int jresult ;
  FrontEnd *arg1 = (FrontEnd *) 0 ;
  mfcc_t *arg2 = (mfcc_t *) 0 ;
  int *arg3 = (int *) 0 ;
  int32 result;
  
  int errcode;
  arg3 = &errcode;
  arg1 = (FrontEnd *)jarg1; 
  arg2 = (mfcc_t *)jarg2; 
  result = FrontEnd_end_utt(arg1,arg2,arg3);
  jresult = result; 
  {
    if (*arg3 < 0) {
      char buf[64];
      sprintf(buf, "FrontEnd_end_utt returned %d", *arg3);
      {
        SWIG_CSharpException(SWIG_RuntimeError, buf); return 0; 
      };
    }
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_Feature(void * jarg1) {
  void * jresult ;
  feat_t *arg1 = (feat_t *) 0 ;
  Feature *result = 0 ;
  
  arg1 = (feat_t *)jarg1; 
  result = (Feature *)new_Feature(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_Feature(void * jarg1) {
  Feature *arg1 = (Feature *) 0 ;
  
  arg1 = (Feature *)jarg1; 
  delete_Feature(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_FsgModel__SWIG_0(char * jarg1, void * jarg2, float jarg3, int jarg4) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  LogMath *arg2 = (LogMath *) 0 ;
  float arg3 ;
  int32 arg4 ;
  FsgModel *result = 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (LogMath *)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (int32)jarg4; 
  result = (FsgModel *)new_FsgModel__SWIG_0((char const *)arg1,arg2,arg3,arg4);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_FsgModel__SWIG_1(void * jarg1) {
  void * jresult ;
  fsg_model_t *arg1 = (fsg_model_t *) 0 ;
  FsgModel *result = 0 ;
  
  arg1 = (fsg_model_t *)jarg1; 
  result = (FsgModel *)new_FsgModel__SWIG_1(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_FsgModel__SWIG_2(char * jarg1, void * jarg2, float jarg3) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  LogMath *arg2 = (LogMath *) 0 ;
  float arg3 ;
  FsgModel *result = 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (LogMath *)jarg2; 
  arg3 = (float)jarg3; 
  result = (FsgModel *)new_FsgModel__SWIG_2((char const *)arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_FsgModel(void * jarg1) {
  FsgModel *arg1 = (FsgModel *) 0 ;
  
  arg1 = (FsgModel *)jarg1; 
  delete_FsgModel(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_FsgModel_word_id(void * jarg1, char * jarg2) {
  int jresult ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (FsgModel *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)FsgModel_word_id(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_FsgModel_word_add(void * jarg1, char * jarg2) {
  int jresult ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (FsgModel *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)FsgModel_word_add(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_FsgModel_trans_add(void * jarg1, int jarg2, int jarg3, int jarg4, int jarg5) {
  FsgModel *arg1 = (FsgModel *) 0 ;
  int32 arg2 ;
  int32 arg3 ;
  int32 arg4 ;
  int32 arg5 ;
  
  arg1 = (FsgModel *)jarg1; 
  arg2 = (int32)jarg2; 
  arg3 = (int32)jarg3; 
  arg4 = (int32)jarg4; 
  arg5 = (int32)jarg5; 
  FsgModel_trans_add(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_FsgModel_null_trans_add(void * jarg1, int jarg2, int jarg3, int jarg4) {
  int jresult ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  int32 arg2 ;
  int32 arg3 ;
  int32 arg4 ;
  int32 result;
  
  arg1 = (FsgModel *)jarg1; 
  arg2 = (int32)jarg2; 
  arg3 = (int32)jarg3; 
  arg4 = (int32)jarg4; 
  result = FsgModel_null_trans_add(arg1,arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_FsgModel_tag_trans_add(void * jarg1, int jarg2, int jarg3, int jarg4, int jarg5) {
  int jresult ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  int32 arg2 ;
  int32 arg3 ;
  int32 arg4 ;
  int32 arg5 ;
  int32 result;
  
  arg1 = (FsgModel *)jarg1; 
  arg2 = (int32)jarg2; 
  arg3 = (int32)jarg3; 
  arg4 = (int32)jarg4; 
  arg5 = (int32)jarg5; 
  result = FsgModel_tag_trans_add(arg1,arg2,arg3,arg4,arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_FsgModel_add_silence(void * jarg1, char * jarg2, int jarg3, float jarg4) {
  int jresult ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  char *arg2 = (char *) 0 ;
  int32 arg3 ;
  float arg4 ;
  int result;
  
  arg1 = (FsgModel *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int32)jarg3; 
  arg4 = (float)jarg4; 
  result = (int)FsgModel_add_silence(arg1,(char const *)arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_FsgModel_add_alt(void * jarg1, char * jarg2, char * jarg3) {
  int jresult ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  arg1 = (FsgModel *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (int)FsgModel_add_alt(arg1,(char const *)arg2,(char const *)arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_FsgModel_writefile(void * jarg1, char * jarg2) {
  FsgModel *arg1 = (FsgModel *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (FsgModel *)jarg1; 
  arg2 = (char *)jarg2; 
  FsgModel_writefile(arg1,(char const *)arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_JsgfRule() {
  void * jresult ;
  JsgfRule *result = 0 ;
  
  result = (JsgfRule *)new_JsgfRule();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_JsgfRule(void * jarg1) {
  JsgfRule *arg1 = (JsgfRule *) 0 ;
  
  arg1 = (JsgfRule *)jarg1; 
  delete_JsgfRule(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_JsgfRule_fromIter(void * jarg1) {
  void * jresult ;
  jsgf_rule_iter_t *arg1 = (jsgf_rule_iter_t *) 0 ;
  JsgfRule *result = 0 ;
  
  arg1 = (jsgf_rule_iter_t *)jarg1; 
  result = (JsgfRule *)JsgfRule_fromIter(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_JsgfRule_name(void * jarg1) {
  char * jresult ;
  JsgfRule *arg1 = (JsgfRule *) 0 ;
  char *result = 0 ;
  
  arg1 = (JsgfRule *)jarg1; 
  result = (char *)JsgfRule_name(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Pocketsphinx_JsgfRule_public_(void * jarg1) {
  unsigned int jresult ;
  JsgfRule *arg1 = (JsgfRule *) 0 ;
  bool result;
  
  arg1 = (JsgfRule *)jarg1; 
  result = (bool)JsgfRule_public(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NGramModel_fromIter(void * jarg1) {
  void * jresult ;
  ngram_model_set_iter_t *arg1 = (ngram_model_set_iter_t *) 0 ;
  NGramModel *result = 0 ;
  
  arg1 = (ngram_model_set_iter_t *)jarg1; 
  result = (NGramModel *)NGramModel_fromIter(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_NGramModel__SWIG_0(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  NGramModel *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (NGramModel *)new_NGramModel__SWIG_0((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_NGramModel__SWIG_1(void * jarg1, void * jarg2, char * jarg3) {
  void * jresult ;
  Config *arg1 = (Config *) 0 ;
  LogMath *arg2 = (LogMath *) 0 ;
  char *arg3 = (char *) 0 ;
  NGramModel *result = 0 ;
  
  arg1 = (Config *)jarg1; 
  arg2 = (LogMath *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (NGramModel *)new_NGramModel__SWIG_1(arg1,arg2,(char const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_NGramModel(void * jarg1) {
  NGramModel *arg1 = (NGramModel *) 0 ;
  
  arg1 = (NGramModel *)jarg1; 
  delete_NGramModel(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_NGramModel_write(void * jarg1, char * jarg2, void * jarg3) {
  NGramModel *arg1 = (NGramModel *) 0 ;
  char *arg2 = (char *) 0 ;
  ngram_file_type_t arg3 ;
  int *arg4 = (int *) 0 ;
  ngram_file_type_t *argp3 ;
  
  int errcode;
  arg4 = &errcode;
  arg1 = (NGramModel *)jarg1; 
  arg2 = (char *)jarg2; 
  argp3 = (ngram_file_type_t *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null ngram_file_type_t", 0);
    return ;
  }
  arg3 = *argp3; 
  NGramModel_write(arg1,(char const *)arg2,arg3,arg4);
  {
    if (*arg4 < 0) {
      char buf[64];
      sprintf(buf, "NGramModel_write returned %d", *arg4);
      {
        SWIG_CSharpException(SWIG_RuntimeError, buf); return ; 
      };
    }
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NGramModel_str_to_type(void * jarg1, char * jarg2) {
  void * jresult ;
  NGramModel *arg1 = (NGramModel *) 0 ;
  char *arg2 = (char *) 0 ;
  ngram_file_type_t result;
  
  arg1 = (NGramModel *)jarg1; 
  arg2 = (char *)jarg2; 
  result = NGramModel_str_to_type(arg1,(char const *)arg2);
  {
    ngram_file_type_t * resultptr = (ngram_file_type_t *) malloc(sizeof(ngram_file_type_t));
    memmove(resultptr, &result, sizeof(ngram_file_type_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_NGramModel_type_to_str(void * jarg1, int jarg2) {
  char * jresult ;
  NGramModel *arg1 = (NGramModel *) 0 ;
  int arg2 ;
  char *result = 0 ;
  
  arg1 = (NGramModel *)jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)NGramModel_type_to_str(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_NGramModel_casefold(void * jarg1, int jarg2) {
  NGramModel *arg1 = (NGramModel *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  
  int errcode;
  arg3 = &errcode;
  arg1 = (NGramModel *)jarg1; 
  arg2 = (int)jarg2; 
  NGramModel_casefold(arg1,arg2,arg3);
  {
    if (*arg3 < 0) {
      char buf[64];
      sprintf(buf, "NGramModel_casefold returned %d", *arg3);
      {
        SWIG_CSharpException(SWIG_RuntimeError, buf); return ; 
      };
    }
  }
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_NGramModel_size(void * jarg1) {
  int jresult ;
  NGramModel *arg1 = (NGramModel *) 0 ;
  int32 result;
  
  arg1 = (NGramModel *)jarg1; 
  result = NGramModel_size(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_NGramModel_add_word(void * jarg1, char * jarg2, void * jarg3) {
  int jresult ;
  NGramModel *arg1 = (NGramModel *) 0 ;
  char *arg2 = (char *) 0 ;
  float32 arg3 ;
  float32 *argp3 ;
  int32 result;
  
  arg1 = (NGramModel *)jarg1; 
  arg2 = (char *)jarg2; 
  argp3 = (float32 *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null float32", 0);
    return 0;
  }
  arg3 = *argp3; 
  result = NGramModel_add_word(arg1,(char const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_NGramModel_prob(void * jarg1, unsigned long jarg2, void * jarg3) {
  int jresult ;
  NGramModel *arg1 = (NGramModel *) 0 ;
  size_t arg2 ;
  char **arg3 = (char **) 0 ;
  int32 result;
  
  arg1 = (NGramModel *)jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (char **)jarg3; 
  result = NGramModel_prob(arg1,arg2,(char const *const *)arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_LogMath__SWIG_0() {
  void * jresult ;
  LogMath *result = 0 ;
  
  result = (LogMath *)new_LogMath__SWIG_0();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_LogMath__SWIG_1(void * jarg1) {
  void * jresult ;
  logmath_t *arg1 = (logmath_t *) 0 ;
  LogMath *result = 0 ;
  
  arg1 = (logmath_t *)jarg1; 
  result = (LogMath *)new_LogMath__SWIG_1(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_LogMath(void * jarg1) {
  LogMath *arg1 = (LogMath *) 0 ;
  
  arg1 = (LogMath *)jarg1; 
  delete_LogMath(arg1);
}


SWIGEXPORT double SWIGSTDCALL CSharp_Pocketsphinx_LogMath_exp(void * jarg1, int jarg2) {
  double jresult ;
  LogMath *arg1 = (LogMath *) 0 ;
  int arg2 ;
  float64 result;
  
  arg1 = (LogMath *)jarg1; 
  arg2 = (int)jarg2; 
  result = LogMath_exp(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_NGramModelSetIterator_ptr_set(void * jarg1, void * jarg2) {
  NGramModelSetIterator *arg1 = (NGramModelSetIterator *) 0 ;
  ngram_model_set_iter_t *arg2 = (ngram_model_set_iter_t *) 0 ;
  
  arg1 = (NGramModelSetIterator *)jarg1; 
  arg2 = (ngram_model_set_iter_t *)jarg2; 
  if (arg1) (arg1)->ptr = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NGramModelSetIterator_ptr_get(void * jarg1) {
  void * jresult ;
  NGramModelSetIterator *arg1 = (NGramModelSetIterator *) 0 ;
  ngram_model_set_iter_t *result = 0 ;
  
  arg1 = (NGramModelSetIterator *)jarg1; 
  result = (ngram_model_set_iter_t *) ((arg1)->ptr);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_NGramModelSetIterator(void * jarg1) {
  void * jresult ;
  ngram_model_set_iter_t *arg1 = (ngram_model_set_iter_t *) 0 ;
  NGramModelSetIterator *result = 0 ;
  
  arg1 = (ngram_model_set_iter_t *)jarg1; 
  result = (NGramModelSetIterator *)new_NGramModelSetIterator(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_NGramModelSetIterator(void * jarg1) {
  NGramModelSetIterator *arg1 = (NGramModelSetIterator *) 0 ;
  
  arg1 = (NGramModelSetIterator *)jarg1; 
  delete_NGramModelSetIterator(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_JsgfIterator_ptr_set(void * jarg1, void * jarg2) {
  JsgfIterator *arg1 = (JsgfIterator *) 0 ;
  jsgf_rule_iter_t *arg2 = (jsgf_rule_iter_t *) 0 ;
  
  arg1 = (JsgfIterator *)jarg1; 
  arg2 = (jsgf_rule_iter_t *)jarg2; 
  if (arg1) (arg1)->ptr = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_JsgfIterator_ptr_get(void * jarg1) {
  void * jresult ;
  JsgfIterator *arg1 = (JsgfIterator *) 0 ;
  jsgf_rule_iter_t *result = 0 ;
  
  arg1 = (JsgfIterator *)jarg1; 
  result = (jsgf_rule_iter_t *) ((arg1)->ptr);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_JsgfIterator(void * jarg1) {
  void * jresult ;
  jsgf_rule_iter_t *arg1 = (jsgf_rule_iter_t *) 0 ;
  JsgfIterator *result = 0 ;
  
  arg1 = (jsgf_rule_iter_t *)jarg1; 
  result = (JsgfIterator *)new_JsgfIterator(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_JsgfIterator(void * jarg1) {
  JsgfIterator *arg1 = (JsgfIterator *) 0 ;
  
  arg1 = (JsgfIterator *)jarg1; 
  delete_JsgfIterator(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NGramModelSet___iter__(void * jarg1) {
  void * jresult ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  NGramModelSetIterator *result = 0 ;
  
  arg1 = (NGramModelSet *)jarg1; 
  result = (NGramModelSetIterator *)NGramModelSet___iter__(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_NGramModelSet(void * jarg1, void * jarg2, char * jarg3) {
  void * jresult ;
  Config *arg1 = (Config *) 0 ;
  LogMath *arg2 = (LogMath *) 0 ;
  char *arg3 = (char *) 0 ;
  NGramModelSet *result = 0 ;
  
  arg1 = (Config *)jarg1; 
  arg2 = (LogMath *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (NGramModelSet *)new_NGramModelSet(arg1,arg2,(char const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_NGramModelSet(void * jarg1) {
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  
  arg1 = (NGramModelSet *)jarg1; 
  delete_NGramModelSet(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_Pocketsphinx_NGramModelSet_count(void * jarg1) {
  int jresult ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  int32 result;
  
  arg1 = (NGramModelSet *)jarg1; 
  result = NGramModelSet_count(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NGramModelSet_add(void * jarg1, void * jarg2, char * jarg3, float jarg4, unsigned int jarg5) {
  void * jresult ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  NGramModel *arg2 = (NGramModel *) 0 ;
  char *arg3 = (char *) 0 ;
  float arg4 ;
  bool arg5 ;
  NGramModel *result = 0 ;
  
  arg1 = (NGramModelSet *)jarg1; 
  arg2 = (NGramModel *)jarg2; 
  arg3 = (char *)jarg3; 
  arg4 = (float)jarg4; 
  arg5 = jarg5 ? true : false; 
  result = (NGramModel *)NGramModelSet_add(arg1,arg2,(char const *)arg3,arg4,arg5);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NGramModelSet_select(void * jarg1, char * jarg2) {
  void * jresult ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  char *arg2 = (char *) 0 ;
  NGramModel *result = 0 ;
  
  arg1 = (NGramModelSet *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (NGramModel *)NGramModelSet_select(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_NGramModelSet_lookup(void * jarg1, char * jarg2) {
  void * jresult ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  char *arg2 = (char *) 0 ;
  NGramModel *result = 0 ;
  
  arg1 = (NGramModelSet *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (NGramModel *)NGramModelSet_lookup(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_NGramModelSet_current(void * jarg1) {
  char * jresult ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  char *result = 0 ;
  
  arg1 = (NGramModelSet *)jarg1; 
  result = (char *)NGramModelSet_current(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Jsgf___iter__(void * jarg1) {
  void * jresult ;
  Jsgf *arg1 = (Jsgf *) 0 ;
  JsgfIterator *result = 0 ;
  
  arg1 = (Jsgf *)jarg1; 
  result = (JsgfIterator *)Jsgf___iter__(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_new_Jsgf(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  Jsgf *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (Jsgf *)new_Jsgf((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Pocketsphinx_delete_Jsgf(void * jarg1) {
  Jsgf *arg1 = (Jsgf *) 0 ;
  
  arg1 = (Jsgf *)jarg1; 
  delete_Jsgf(arg1);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_Pocketsphinx_Jsgf_name(void * jarg1) {
  char * jresult ;
  Jsgf *arg1 = (Jsgf *) 0 ;
  char *result = 0 ;
  
  arg1 = (Jsgf *)jarg1; 
  result = (char *)Jsgf_name(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Jsgf_get_rule(void * jarg1, char * jarg2) {
  void * jresult ;
  Jsgf *arg1 = (Jsgf *) 0 ;
  char *arg2 = (char *) 0 ;
  JsgfRule *result = 0 ;
  
  arg1 = (Jsgf *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (JsgfRule *)Jsgf_get_rule(arg1,(char const *)arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Pocketsphinx_Jsgf_build_fsg(void * jarg1, void * jarg2, void * jarg3, float jarg4) {
  void * jresult ;
  Jsgf *arg1 = (Jsgf *) 0 ;
  JsgfRule *arg2 = (JsgfRule *) 0 ;
  LogMath *arg3 = (LogMath *) 0 ;
  float arg4 ;
  FsgModel *result = 0 ;
  
  arg1 = (Jsgf *)jarg1; 
  arg2 = (JsgfRule *)jarg2; 
  arg3 = (LogMath *)jarg3; 
  arg4 = (float)jarg4; 
  result = (FsgModel *)Jsgf_build_fsg(arg1,arg2,arg3,arg4);
  jresult = (void *)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

