//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Pocketsphinx {

public class Jsgf : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Jsgf(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Jsgf obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Jsgf() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          sphinxbasePINVOKE.delete_Jsgf(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public JsgfIterator __iter__() {
    global::System.IntPtr cPtr = sphinxbasePINVOKE.Jsgf___iter__(swigCPtr);
    JsgfIterator ret = (cPtr == global::System.IntPtr.Zero) ? null : new JsgfIterator(cPtr, true);
    return ret;
  }

  public Jsgf(string path) : this(sphinxbasePINVOKE.new_Jsgf(path), true) {
  }

  public string name() {
    string ret = sphinxbasePINVOKE.Jsgf_name(swigCPtr);
    return ret;
  }

  public JsgfRule get_rule(string name) {
    global::System.IntPtr cPtr = sphinxbasePINVOKE.Jsgf_get_rule(swigCPtr, name);
    JsgfRule ret = (cPtr == global::System.IntPtr.Zero) ? null : new JsgfRule(cPtr, false);
    return ret;
  }

  public FsgModel build_fsg(JsgfRule rule, LogMath logmath, float lw) {
    global::System.IntPtr cPtr = sphinxbasePINVOKE.Jsgf_build_fsg(swigCPtr, JsgfRule.getCPtr(rule), LogMath.getCPtr(logmath), lw);
    FsgModel ret = (cPtr == global::System.IntPtr.Zero) ? null : new FsgModel(cPtr, false);
    return ret;
  }

}

}
