//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Pocketsphinx {

public class Segment : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Segment(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Segment obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Segment() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PocketSphinxPINVOKE.delete_Segment(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

    public override string ToString() {
	return word + " " + start_frame + " " + end_frame + " " + prob;
    }

  public string word {
    set {
      PocketSphinxPINVOKE.Segment_word_set(swigCPtr, value);
    } 
    get {
      string ret = PocketSphinxPINVOKE.Segment_word_get(swigCPtr);
      return ret;
    } 
  }

  public int ascore {
    set {
      PocketSphinxPINVOKE.Segment_ascore_set(swigCPtr, value);
    } 
    get {
      int ret = PocketSphinxPINVOKE.Segment_ascore_get(swigCPtr);
      return ret;
    } 
  }

  public int lscore {
    set {
      PocketSphinxPINVOKE.Segment_lscore_set(swigCPtr, value);
    } 
    get {
      int ret = PocketSphinxPINVOKE.Segment_lscore_get(swigCPtr);
      return ret;
    } 
  }

  public int lback {
    set {
      PocketSphinxPINVOKE.Segment_lback_set(swigCPtr, value);
    } 
    get {
      int ret = PocketSphinxPINVOKE.Segment_lback_get(swigCPtr);
      return ret;
    } 
  }

  public int prob {
    set {
      PocketSphinxPINVOKE.Segment_prob_set(swigCPtr, value);
    } 
    get {
      int ret = PocketSphinxPINVOKE.Segment_prob_get(swigCPtr);
      return ret;
    } 
  }

  public int start_frame {
    set {
      PocketSphinxPINVOKE.Segment_start_frame_set(swigCPtr, value);
    } 
    get {
      int ret = PocketSphinxPINVOKE.Segment_start_frame_get(swigCPtr);
      return ret;
    } 
  }

  public int end_frame {
    set {
      PocketSphinxPINVOKE.Segment_end_frame_set(swigCPtr, value);
    } 
    get {
      int ret = PocketSphinxPINVOKE.Segment_end_frame_get(swigCPtr);
      return ret;
    } 
  }

  public static Segment fromIter(SWIGTYPE_p_void itor) {
    global::System.IntPtr cPtr = PocketSphinxPINVOKE.Segment_fromIter(SWIGTYPE_p_void.getCPtr(itor));
    Segment ret = (cPtr == global::System.IntPtr.Zero) ? null : new Segment(cPtr, false);
    return ret;
  }

  public Segment() : this(PocketSphinxPINVOKE.new_Segment(), true) {
  }

}

}
